/* eslint-disable ts/no-explicit-any */
/* eslint-disable ts/no-unsafe-member-access */
/* eslint-disable ts/no-extraneous-class */

import { format } from 'date-fns'
import fs from 'fs-extra'
import path from 'node:path'
import { z } from 'zod'
import type { snipSchema, snipsSchema } from '../schemas.js'
import { HOME_DIRECTORY } from '../constants.js'
import packageInfo from '../generated/package-info.json' with { type: 'json' }
import vscodeLanguageMap from '../generated/vscode-language-map.json' with { type: 'json' }
import { log } from '../log.js'

const languageIdsByExtension: Record<string, string[]> = vscodeLanguageMap

// Type EditorAdapter<T extends z.ZodTypeAny, U extends z.ZodTypeAny> = {
//   type: z.infer<typeof Editor>;
//   fileSchema: U;
//   editorSnipSchema: T;
//   snipToEditor(snip: z.infer<typeof snipSchema>): T;
//   editorToSnip(editorSnip: T): z.infer<typeof snipSchema>;
// };

export class VscodeAdapter {
	private static readonly editorExtensionManifestSnipsSchema = z.array(
		z.object({
			language: z.string().min(1),
			path: z.string().min(1),
		}),
	) // TODO Windows

	// TODO how to deal with records...
	private static readonly editorSnipsSchema = z.record(
		z.string().min(1),
		z.object({
			body: z.array(z.string()),
			description: z.string().min(1).optional(),
			prefix: z.string().min(1).optional(),
			scope: z.string().min(1).optional(),
		}),
	)

	// Constants
	private static readonly vscodeUserExtensionsDir = `${HOME_DIRECTORY}/.vscode/extensions`
	private static readonly vscodeUserSnippetsDir = `${HOME_DIRECTORY}/Library/Application Support/Code/User/snippets`

	// Transformers
	public static async getSnipsFromEditor(): Promise<z.infer<typeof snipsSchema>> {
		const extensionSnips = this.getSnipsFromExtensions()
		log.debug(`extensionSnips: ${JSON.stringify(extensionSnips, undefined, 2)}`)

		// TODO
		const userSnips = this.getSnipsFromUser()
		log.debug(`userSnips: ${JSON.stringify(userSnips, undefined, 2)}`)

		return extensionSnips
	}

	// Methods
	public static async writeSnipsToEditor(snips: z.infer<typeof snipsSchema>): Promise<void> {
		const vscodeSnippets: z.infer<typeof this.editorSnipsSchema> = {}

		for (const snip of snips) {
			const editorSnip = this.convertSnipToEditorSnip(snip)

			Object.assign(vscodeSnippets, editorSnip)
		}

		const content = `/* This file of ${Object.keys(vscodeSnippets).length} snippets was generated by ${packageInfo.command} v${packageInfo.version} on ${format(new Date(), "yyyy-MM-dd 'at' HH:mm:ss")} */\n${JSON.stringify(
			vscodeSnippets,
			undefined,
			2,
		)}`

		// Log.debug(content);
		// TODO flag overwrite
		// TODO check directory exists
		await fs.writeFile(`${this.vscodeUserSnippetsDir}/snip.code-snippets`, content)

		log.debug(`Wrote ${snips.length} snips to VS Code`)
	}

	// TODO zod way to do this?
	private static convertEditorSnipToSnip(
		editorSnip: z.infer<typeof this.editorSnipsSchema>,
	): z.infer<typeof snipSchema> {
		const [value] = Object.values(editorSnip)
		if (!value) {
			throw new Error('Cannot convert an empty editor snippet')
		}

		const snip: z.infer<typeof snipSchema> = {
			all: false, // TODO
			body: value.body.join('\n'),
			description: value.description,
			extensions: [], // TODO reverse lookup!!!
			prefix: value.prefix,
		}

		return snip
	}

	private static convertSnipToEditorSnip(
		snip: z.infer<typeof snipSchema>,
	): z.infer<typeof this.editorSnipsSchema> {
		const key = snip.description ?? snip.prefix ?? `Key From Snip ${Date.now()}` // TODO hmm
		const vscodeSnippet: z.infer<typeof this.editorSnipsSchema> = {}

		// eslint-disable-next-line unicorn/no-immediate-mutation
		vscodeSnippet[key] = {
			body: snip.body.split('\n'),
			prefix: snip.prefix,
		}

		if (!snip.all && snip.extensions && snip.extensions.length > 0) {
			vscodeSnippet[key].scope = this.vscodeLanguageIdsForExtensions(snip.extensions).join(',')
		}

		if (snip.description !== undefined && snip.description !== '') {
			vscodeSnippet[key].description = snip.description
		}

		return vscodeSnippet
	}

	private static async getSnipsFromExtensions(): Promise<z.infer<typeof snipsSchema>> {
		log.debug(`vscodeUserExtensionsDir: ${this.vscodeUserExtensionsDir}`)
		// Scan extensions folder for snippets
		// All snippet extensions I can find use .json snippet files instead of .code-snippets...
		// TODO a GH search to see if that's really the case

		// Returns an array of objects keyed to the extension path
		// TODO walk or something more efficient...

		const snips: z.infer<typeof snipsSchema> = []

		const extensions = await fs.readdir(this.vscodeUserExtensionsDir)
		for (const directory of extensions) {
			const packagePath = path.join(this.vscodeUserExtensionsDir, directory, 'package.json')
			if (!(await fs.exists(packagePath))) {
				continue
			}

			const manifest = (await fs.readJSON(packagePath)) as Record<string, any>
			const hasSnippets = Boolean(manifest.contributes?.snippets)
			if (!hasSnippets) {
				continue
			}

			log.debug(`${manifest.name} contributes snippets...`)

			try {
				const extensionSnippets = this.editorExtensionManifestSnipsSchema.parse(
					manifest.contributes.snippets,
				)

				for (const extensionSnippet of extensionSnippets) {
					const extensionSnippetPath = path.join(path.dirname(packagePath), extensionSnippet.path)

					log.debug(`Loading "${extensionSnippetPath}"`)

					const extensionSnips = this.editorSnipsSchema.parse(
						await fs.readJSON(extensionSnippetPath),
					)

					for (const [key, value] of Object.entries(extensionSnips)) {
						const snip = this.convertEditorSnipToSnip({ [key]: value })
						snips.push(snip)
					}

					// Console.log(`extensionSnips: ${extensionSnips}`);
				}
			} catch {
				log.error(`Error parsing snippets from ${directory}`)
				// Console.error(`error: ${JSON.stringify(error, undefined, 2)}`)
			}
		}

		return snips
	}

	// eslint-disable-next-line ts/require-await
	private static async getSnipsFromUser(): Promise<z.infer<typeof snipsSchema>> {
		// TODO
		// Back up existing vscode snippets
		// try {
		// 	await fs.copy(
		// 		this.vscodeUserSnippetsDir,
		// 		`${SNIP_LIBRARY_DIR}/backups/vscode/${Date.now()}`,
		// 	)
		// } catch (error) {
		// 	console.log(`Error backing up user snippets: ${String(error)}`)
		// }

		// const vscodeFiles = await fs.readdir(this.vscodeUserSnippetsDir)
		// const vscodeFormattedFiles = vscodeFiles
		// 	.filter((f) => f !== '.DS_Store')
		// 	.reduce(async (previous, file) => {
		// 		const acc = previous
		// 		const lang = file.split('.')[0]
		// 		acc[lang] = await fs.read(`${this.vscodeUserSnippetsDir}/${file}`)
		// 		return acc
		// 	}, {})

		log.warn('getSnipsFromUser not implemented')

		return []
	}

	// Helpers
	private static vscodeLanguageIdsForExtensions(extensions: string[]): string[] {
		const languageIds = new Set<string>()

		for (const extension of extensions) {
			// Dot prefix
			const key = `.${extension}`
			const matchingLanguageIds = languageIdsByExtension[key]
			if (matchingLanguageIds === undefined) {
				log.warn(`No VS Code language id for extension ${extension}`)
				continue
			}

			for (const languageId of matchingLanguageIds) {
				languageIds.add(languageId)
			}
		}

		return [...languageIds]
	}
}
