/* eslint-disable no-template-curly-in-string */
/* eslint-disable ts/no-unsafe-member-access */
/* eslint-disable ts/no-unsafe-assignment */

import fs from 'fs-extra'
import os from 'node:os'
import path from 'node:path'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'

async function createTempDirectory(prefix: string): Promise<string> {
	return fs.mkdtemp(path.join(os.tmpdir(), `snip-test-${prefix}-`))
}

describe('VscodeAdapter', () => {
	let tempExtensionsDirectory: string
	let tempSnippetsDirectory: string

	beforeEach(async () => {
		tempExtensionsDirectory = await createTempDirectory('vscode-ext')
		tempSnippetsDirectory = await createTempDirectory('vscode-snip')
	})

	afterEach(async () => {
		vi.restoreAllMocks()
		await fs.remove(tempExtensionsDirectory)
		await fs.remove(tempSnippetsDirectory)
	})

	describe('writeSnipsToEditor', () => {
		it('writes snips to the VS Code snippets directory', async () => {
			const { VscodeAdapter } = await import('../../src/adapters/vscode')

			Object.defineProperty(VscodeAdapter, 'vscodeUserSnippetsDir', {
				configurable: true,
				value: tempSnippetsDirectory,
			})

			const snips = [
				{
					all: false,
					body: 'console.log($1);$0',
					description: 'Print value console',
					extensions: ['js', 'ts'],
					prefix: 'cl',
				},
				{
					all: true,
					body: 'Lorem ipsum dolor sit amet',
					description: 'Lorem Ipsum',
					extensions: [],
					prefix: 'li',
				},
			]

			await VscodeAdapter.writeSnipsToEditor(snips)

			const outputPath = path.join(tempSnippetsDirectory, 'snip.code-snippets')
			expect(await fs.exists(outputPath)).toBe(true)

			const content = await fs.readFile(outputPath, 'utf8')
			expect(content).toContain('snippets was generated by')
			expect(content).toContain('snip')

			const jsonStart = content.indexOf('{')
			const json = JSON.parse(content.slice(jsonStart))

			expect(json['Print value console']).toBeDefined()
			expect(json['Print value console'].prefix).toBe('cl')
			expect(json['Print value console'].body).toEqual(['console.log($1);$0'])
			expect(json['Print value console'].scope).toContain('javascript')
			expect(json['Print value console'].scope).toContain('typescript')
			expect(json['Print value console'].description).toBe('Print value console')

			expect(json['Lorem Ipsum']).toBeDefined()
			expect(json['Lorem Ipsum'].prefix).toBe('li')
			expect(json['Lorem Ipsum'].scope).toBeUndefined()
		})

		it('handles multiline snippet bodies', async () => {
			const { VscodeAdapter } = await import('../../src/adapters/vscode')

			Object.defineProperty(VscodeAdapter, 'vscodeUserSnippetsDir', {
				configurable: true,
				value: tempSnippetsDirectory,
			})

			const snips = [
				{
					all: false,
					body: '<!doctype html>\n<html>\n<body>\n$0\n</body>\n</html>',
					description: 'HTML boilerplate',
					extensions: ['html'],
					prefix: 'html',
				},
			]

			await VscodeAdapter.writeSnipsToEditor(snips)

			const outputPath = path.join(tempSnippetsDirectory, 'snip.code-snippets')
			const content = await fs.readFile(outputPath, 'utf8')
			const jsonStart = content.indexOf('{')
			const json = JSON.parse(content.slice(jsonStart))

			expect(json['HTML boilerplate'].body).toEqual([
				'<!doctype html>',
				'<html>',
				'<body>',
				'$0',
				'</body>',
				'</html>',
			])
		})

		it('handles empty snips array', async () => {
			const { VscodeAdapter } = await import('../../src/adapters/vscode')

			Object.defineProperty(VscodeAdapter, 'vscodeUserSnippetsDir', {
				configurable: true,
				value: tempSnippetsDirectory,
			})

			await VscodeAdapter.writeSnipsToEditor([])

			const outputPath = path.join(tempSnippetsDirectory, 'snip.code-snippets')
			expect(await fs.exists(outputPath)).toBe(true)

			const content = await fs.readFile(outputPath, 'utf8')
			expect(content).toContain('0 snippets was generated by')
		})
	})

	describe('getSnipsFromEditor', () => {
		it('reads snippets from VS Code extensions', async () => {
			const { VscodeAdapter } = await import('../../src/adapters/vscode')

			Object.defineProperty(VscodeAdapter, 'vscodeUserExtensionsDir', {
				configurable: true,
				value: tempExtensionsDirectory,
			})

			const extensionDirectory = path.join(tempExtensionsDirectory, 'test-extension-1.0.0')
			await fs.ensureDir(extensionDirectory)
			await fs.ensureDir(path.join(extensionDirectory, 'snippets'))

			const snippetContent = {
				'Console Log': {
					body: ['console.log($1)'],
					description: 'Log output to console',
					prefix: 'log',
					scope: 'javascript,typescript',
				},
				'For Loop': {
					body: ['for (let ${1:i} = 0; $1 < ${2:length}; $1++) {', '\t$0', '}'],
					description: 'For loop',
					prefix: 'for',
					scope: 'javascript',
				},
			}
			await fs.writeJSON(
				path.join(extensionDirectory, 'snippets', 'javascript.json'),
				snippetContent,
			)

			const packageJson = {
				contributes: {
					snippets: [
						{
							language: 'javascript',
							path: './snippets/javascript.json',
						},
					],
				},
				name: 'test-extension',
				version: '1.0.0',
			}
			await fs.writeJSON(path.join(extensionDirectory, 'package.json'), packageJson)

			const snips = await VscodeAdapter.getSnipsFromEditor()

			expect(snips).toHaveLength(2)

			const logSnip = snips.find((s) => s.prefix === 'log')
			expect(logSnip).toBeDefined()
			expect(logSnip!.body).toBe('console.log($1)')
			expect(logSnip!.description).toBe('Log output to console')

			const forSnip = snips.find((s) => s.prefix === 'for')
			expect(forSnip).toBeDefined()
			expect(forSnip!.body).toContain('for (let')
		})

		it('handles extensions directory with no snippet extensions', async () => {
			const { VscodeAdapter } = await import('../../src/adapters/vscode')

			Object.defineProperty(VscodeAdapter, 'vscodeUserExtensionsDir', {
				configurable: true,
				value: tempExtensionsDirectory,
			})

			const extensionDirectory = path.join(tempExtensionsDirectory, 'theme-extension-1.0.0')
			await fs.ensureDir(extensionDirectory)
			await fs.writeJSON(path.join(extensionDirectory, 'package.json'), {
				contributes: { themes: [] },
				name: 'theme-extension',
				version: '1.0.0',
			})

			const snips = await VscodeAdapter.getSnipsFromEditor()
			expect(snips).toEqual([])
		})

		it('handles empty extensions directory', async () => {
			const { VscodeAdapter } = await import('../../src/adapters/vscode')

			Object.defineProperty(VscodeAdapter, 'vscodeUserExtensionsDir', {
				configurable: true,
				value: tempExtensionsDirectory,
			})

			const snips = await VscodeAdapter.getSnipsFromEditor()
			expect(snips).toEqual([])
		})

		it('handles multiple extensions with snippets', async () => {
			const { VscodeAdapter } = await import('../../src/adapters/vscode')

			Object.defineProperty(VscodeAdapter, 'vscodeUserExtensionsDir', {
				configurable: true,
				value: tempExtensionsDirectory,
			})

			const jsExtensionDirectory = path.join(tempExtensionsDirectory, 'js-snippets-1.0.0')
			await fs.ensureDir(path.join(jsExtensionDirectory, 'snippets'))
			await fs.writeJSON(path.join(jsExtensionDirectory, 'snippets', 'js.json'), {
				'Arrow Function': {
					body: ['const ${1:name} = ($2) => {', '\t$0', '}'],
					prefix: 'af',
				},
			})
			await fs.writeJSON(path.join(jsExtensionDirectory, 'package.json'), {
				contributes: {
					snippets: [{ language: 'javascript', path: './snippets/js.json' }],
				},
				name: 'js-snippets',
				version: '1.0.0',
			})

			const htmlExtensionDirectory = path.join(tempExtensionsDirectory, 'html-snippets-1.0.0')
			await fs.ensureDir(path.join(htmlExtensionDirectory, 'snippets'))
			await fs.writeJSON(path.join(htmlExtensionDirectory, 'snippets', 'html.json'), {
				'HTML5 Template': {
					body: ['<!doctype html>', '<html>', '</html>'],
					prefix: 'html5',
				},
			})
			await fs.writeJSON(path.join(htmlExtensionDirectory, 'package.json'), {
				contributes: {
					snippets: [{ language: 'html', path: './snippets/html.json' }],
				},
				name: 'html-snippets',
				version: '1.0.0',
			})

			const snips = await VscodeAdapter.getSnipsFromEditor()
			expect(snips).toHaveLength(2)

			const prefixes = snips
				.map((s) => s.prefix)
				.toSorted((a, b) => (a ?? '').localeCompare(b ?? ''))
			expect(prefixes).toEqual(['af', 'html5'])
		})

		it('gracefully handles malformed extension package.json', async () => {
			const { VscodeAdapter } = await import('../../src/adapters/vscode')

			Object.defineProperty(VscodeAdapter, 'vscodeUserExtensionsDir', {
				configurable: true,
				value: tempExtensionsDirectory,
			})

			const extensionDirectory = path.join(tempExtensionsDirectory, 'broken-ext-1.0.0')
			await fs.ensureDir(extensionDirectory)
			await fs.writeJSON(path.join(extensionDirectory, 'package.json'), {
				contributes: {
					snippets: [{ language: 'javascript', path: './nonexistent/snippets.json' }],
				},
				name: 'broken-ext',
				version: '1.0.0',
			})

			const snips = await VscodeAdapter.getSnipsFromEditor()
			expect(snips).toEqual([])
		})
	})
})
